### ISSUE TITLE
Cannot profile programs with arguments

### ISSUE THREAD

**Issue by thedrow** [what-studio/profiling#18]
python -m profiling live-profile -i 5 ./runtests.py '-k test_full_stack_benchmarks.py -v --bench --bench-only'
Usage: __main__.py live-profile [OPTIONS] SCRIPT [ARGV]...

Error: no such option: -k

**Comment by sublee** [comment]
Can you try with ``--``?

```bash
$ python -m profiling live-profiling -i 5 -- runtests.py -k test_full_stack_benchmarks.py -v --bench --bench-only
```

**Comment by boulund** [comment]
Using ``--`` worked for me! Is this information available somewhere in the documentation?

**Comment by thedrow** [comment]
It is now somewhat available but should be added to the readme as well.

**Comment by sublee** [comment]
I changed the CLI usage at e361844. I'll update the readme also soon.

**Comment by thedrow** [comment]
Wonderful :)

**Comment by sublee** [comment]
Readme updated at 8a845e3.
