### ISSUE TITLE
Getting a usage error when I try and profile my testharness

### ISSUE THREAD

**Issue by rcowham** [what-studio/profiling#23]
Getting a usage error when I try and profile my tests:

python -m profiling TestTransfer.py
Usage: __main__.py [OPTIONS] COMMAND [ARGS]...

Obviously just running without profile works. The test harness does the usual:

```
if __name__ == '__main__':
    unittest.main()
```

**Comment by sublee** [comment]
You should execute the ``profile`` sub-command.

```sh
$ python -m profiling profile TestTransfer.py
```

**Comment by sublee** [comment]
#18 seems the same issue.
