### ISSUE TITLE
Add profiling to PyPI

### ISSUE THREAD

**Issue by hfaran** [what-studio/profiling#24]
I realize the README says this: "This project is still under development, so you should install it via GitHub instead of PyPI:" but IMO, `profiling` is definitely in a good enough position where a stable release can be thrown onto PyPI.

**Comment by dahlia** [comment]
+1

**Comment by sublee** [comment]
I'll release this project when I implement a sampling profiler.  Please wait for a little more.

**Comment by sublee** [comment]
https://github.com/what-studio/profiling/releases/tag/0.1.1

Now you can install `profiling` via PyPI.
