### ISSUE TITLE
pip install fails on Windows

### ISSUE THREAD

**Issue by suurjaak** [what-studio/profiling#29]
Attempt to install profiling on Windows 7, Python 2.7 (32bit):

    building 'profiling.speedup' extension
    creating build\temp.win32-2.7
    creating build\temp.win32-2.7\Release
    creating build\temp.win32-2.7\Release\profiling
    C:\Program Files\TDM-GCC\bin\gcc.exe -mno-cygwin -mdll -O -Wall "-IC:\Program Files (x86)\Python\include" "-IC:\Program Files (x86)\Python\PC" -c profiling/speedup.c -o build\temp.win32-2.7\Release\profiling\speedup.o
    gcc: error: unrecognized command line option '-mno-cygwin'

Tried with MinGW-gcc 4.7.2, and TDM-gcc 4.8 and 5.1.

**Comment by sublee** [comment]
Thanks to report. But now I have no plan to support Windows yet. After the first release, I'll think about this issue again. Sorry.

**Comment by suurjaak** [comment]
In that case, could you please amend the README so that it says which platforms are supported?

**Comment by sublee** [comment]
Sure.  I should have done so.
