### ISSUE TITLE
`NoneType` when using live-profile

### ISSUE THREAD

**Issue by otrenav** [what-studio/profiling#35]
When I run `$ profiling live-profile manage.py runserver` on a tweaked `manage.py` file that only prints the current path, I get

```
Exception TypeError: "'NoneType' object is not callable" in <function _remove at 0x7f75f23457d0> ignored
```

The contents of `manage.py` are:

```
#!/usr/bin/env python
import os
import sys

if __name__ == "__main__":
    from pprint import pprint as p
    p(sys.path)

    # os.environ.setdefault("DJANGO_SETTINGS_MODULE", "test_app.settings")
    # from django.core.management import execute_from_command_line
    # execute_from_command_line(sys.argv)
```

For replication (in case you are not familiar with Django): you can start a brand new Django 1.7 project with `$ django-admin startproject test_app` and then tweak `manage.py` to only figure what the path is.

**Comment by sublee** [comment]
I think that this issue is similar to #34.  Would you check it?

**Comment by otrenav** [comment]
Indeed, it's similar to that issue; however, since behavior is distinct I thought I would report it separately. We can continue on that issue since the solutions will probably be very similar, if not the same.
