### ISSUE TITLE
Profiling of asyncio application failing

### ISSUE THREAD

**Issue by kharidiron** [what-studio/profiling#38]
I'm trying to profile a (rather complex) asyncio application (https://github.com/kharidiron/StarryPy3k) and am running into the issue that profiling will not import from other files in the same directory.

> $ profiling live-profile --eventloop-aware=asyncio server.py
> 
> Traceback (most recent call last):
>   File "/Users/kharidiron/Workspace/PyCharm/VEnvs/StarryPy3k/bin/profiling", line 9, in <module>
>     load_entry_point('profiling==0.0.0.dev0', 'console_scripts', 'profiling')()
>   File "/Users/kharidiron/Workspace/PyCharm/VEnvs/StarryPy3k/lib/python3.5/site-packages/click/core.py", line 716, in __call__
>     return self.main(*args, **kwargs)
>   File "/Users/kharidiron/Workspace/PyCharm/VEnvs/StarryPy3k/lib/python3.5/site-packages/click/core.py", line 696, in main
>     rv = self.invoke(ctx)
>   File "/Users/kharidiron/Workspace/PyCharm/VEnvs/StarryPy3k/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/Users/kharidiron/Workspace/PyCharm/VEnvs/StarryPy3k/lib/python3.5/site-packages/click/core.py", line 889, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/Users/kharidiron/Workspace/PyCharm/VEnvs/StarryPy3k/lib/python3.5/site-packages/click/core.py", line 534, in invoke
>     return callback(*args, **kwargs)
>   File "/Users/kharidiron/Workspace/PyCharm/VEnvs/StarryPy3k/lib/python3.5/site-packages/profiling/__main__.py", line 525, in wrapped
>     return f(**kwargs)
>   File "/Users/kharidiron/Workspace/PyCharm/VEnvs/StarryPy3k/lib/python3.5/site-packages/profiling/__main__.py", line 502, in wrapped
>     return f(profiler_factory=profiler_factory, **kwargs)
>   File "/Users/kharidiron/Workspace/PyCharm/VEnvs/StarryPy3k/lib/python3.5/site-packages/profiling/__main__.py", line 679, in live_profile
>     exec_(code, globals_)
>   File "server.py", line 5, in <module>
>     from configuration_manager import ConfigurationManager
> ImportError: No module named 'configuration_manager'

Am I doing something wrong?

(edit formatting)

**Comment by sublee** [comment]
Thank you for the report.  It is a bug which was fixed at df2fc23 on the `master` branch.  I cherry-picked that on the `eventloop-aware` branch.  Would you try to pull it?

**Comment by kharidiron** [comment]
Yup, that fixed it. :3

Cheers and thanks for the quick reply.
